/*
 * This source file was generated by the Gradle 'init' task
 */
package org.xoelrp.tetris;

import javax.swing.JFrame;

import org.xoelrp.tetris.game_panel.GamePanel;

public class App {

    public static void main(String[] args) {
        
        JFrame window = new JFrame("Tetris");
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setResizable(false);

        // Add GamePanel to the window
        GamePanel gamePanel = new GamePanel();
        window.add(gamePanel);
        window.pack(); // Ajusta la ventana al tamaño de sus componentes

        window.setLocationRelativeTo(null);
        window.setVisible(true);

        gamePanel.launchGame();
    }
}
